const SEED_PROFILES = [
  {
    id: "P1",
    name: "Ranveer Singh Rathore",
    gender: "Groom",
    age: 28,
    height: "6'1\"",
    caste: "Rajput",
    gotra: "Rathore (Father) / Chauhan (Mother)",
    native: "Jodhpur, Rajasthan",
    rashi: "Leo (Simha)",
    nakshatra: "Purva Phalguni",
    manglik: "Non-Manglik",
    education: "MBA - IIM Ahmedabad, B.Tech - IIT Bombay",
    occupation: "Co-Founder, Royal Heritage Resorts & Tech Startups",
    income: "₹85 Lakhs PA",
    location: "Jaipur, Rajasthan",
    familyType: "Royal Heritage",
    familyDetails: "Father is an established hotelier and ancestral landowner in Jodhpur. Mother is from a respectable royal Chauhan family of Bundi. One younger sister (married to an IAS officer).",
    about: "Believer in blending our rich Rajputana traditions with a progressive, modern worldview. Passionate about heritage preservation, equestrian sports, and expanding our sustainable tourism venture. Looking for an elegant partner who shares a deep respect for values and culture.",
    expectations: "An educated, warm, and graceful lady who values family ties, culture, and possesses a progressive outlook. Mutual respect and understanding are paramount.",
    initials: "RS",
    img: "images/groom_ranveer.png",
    isRecentlyActive: true,
    isVerified: true,
    aiScore: 98
  },
  {
    id: "P2",
    name: "Aishwarya Shekhawat",
    gender: "Bride",
    age: 26,
    height: "5'7\"",
    caste: "Rajput",
    gotra: "Shekhawat (Father) / Sisodia (Mother)",
    native: "Sikar, Rajasthan",
    rashi: "Taurus (Vrishabha)",
    nakshatra: "Rohini",
    manglik: "Non-Manglik",
    education: "M.A. in History & Fine Arts - Maharaja Sayajirao University",
    occupation: "Restoration Architect & Art Historian",
    income: "₹18 Lakhs PA",
    location: "Udaipur, Rajasthan",
    familyType: "Royal Heritage",
    familyDetails: "Father is a retired Colonel from the Indian Army and a traditional landowner. Mother is a homemaker from an noble Sisodia lineage. One elder brother running real estate in Gurgaon.",
    about: "Cultured, soft-spoken, and creative, I spend my days restoring heritage murals and forts in Rajasthan. I am deeply rooted in Mewar heritage but equally appreciative of modern art, literature, and travel. I love horse riding and classical music.",
    expectations: "A noble gentleman from a respectable family, preferably Rajput, who is well-educated, progressive, and respects my professional passion for art and heritage.",
    initials: "AS",
    img: "images/bride_aishwarya.png",
    isRecentlyActive: true,
    isVerified: true,
    aiScore: 96
  },
  {
    id: "P3",
    name: "Devendra Sharma",
    gender: "Groom",
    age: 29,
    height: "5'11\"",
    caste: "Brahmin",
    gotra: "Bhardwaj (Father) / Shandilya (Mother)",
    native: "Jaipur, Rajasthan",
    rashi: "Aries (Mesha)",
    nakshatra: "Ashwini",
    manglik: "Non-Manglik",
    education: "M.S. in Computer Science - Stanford University",
    occupation: "Senior AI Research Scientist, Google",
    income: "₹1.2 Crores PA",
    location: "San Francisco, USA",
    familyType: "Traditional",
    familyDetails: "Father is a Senior Professor at Rajasthan University. Mother is a Sanskrit scholar. Younger brother is a cardiologist in Delhi.",
    about: "Simple, highly intellectual, yet deeply connected to my spiritual roots. I perform daily sandhyavandanam but live at the cutting edge of tech. I enjoy reading Vedic literature, hiking, and playing the sitar.",
    expectations: "A well-educated, intellectually compatible, and culturally-rooted lady who is willing to relocate or is already in the US. A background in science/arts is highly appreciated.",
    initials: "DS",
    img: "images/groom_devendra.png",
    isRecentlyActive: false,
    isVerified: true,
    aiScore: 94
  },
  {
    id: "P4",
    name: "Priyanka Chaturvedi",
    gender: "Bride",
    age: 25,
    height: "5'4\"",
    caste: "Brahmin",
    gotra: "Gautam (Father) / Kashyap (Mother)",
    native: "Ajmer, Rajasthan",
    rashi: "Cancer (Karka)",
    nakshatra: "Pushya",
    manglik: "Non-Manglik",
    education: "M.D. Pediatrics - SMS Medical College, Jaipur",
    occupation: "Resident Pediatrician",
    income: "₹15 Lakhs PA",
    location: "Jaipur, Rajasthan",
    familyType: "Traditional",
    familyDetails: "Father is a practicing Senior Advocate in Rajasthan High Court. Mother is a retired government school Principal. Two elder sisters, both happily married.",
    about: "Compassionate, bubbly, and dedicated to children's healthcare. I believe in mutual growth and keeping the family together with love. I enjoy classical Kathak and cooking traditional Rajasthani dishes.",
    expectations: "An understanding and compassionate groom, preferably a Doctor or a well-placed professional, who values ethical living, humor, and respect.",
    initials: "PC",
    img: "images/bride_priyanka.png",
    isRecentlyActive: true,
    isVerified: true,
    aiScore: 95
  },
  {
    id: "P5",
    name: "Aditya Maheshwari",
    gender: "Groom",
    age: 27,
    height: "5'10\"",
    caste: "Maheshwari",
    gotra: "Ajmera (Father) / Sarda (Mother)",
    native: "Bikaner, Rajasthan",
    rashi: "Libra (Tula)",
    nakshatra: "Chitra",
    manglik: "Non-Manglik",
    education: "Chartered Accountant (CA) - All India Ranker",
    occupation: "Partner, Leading Audit Firm & Investor",
    income: "₹55 Lakhs PA",
    location: "Mumbai, Maharashtra",
    familyType: "Traditional",
    familyDetails: "Family owns major spice businesses and cold storages in Bikaner. Mother is a homemaker. Younger sister is pursuing her CA.",
    about: "Ambitious and business-minded yet down-to-earth and family-centric. I love exploring new financial markets, playing squash, and hosting family gatherings. I believe in building a strong foundation of trust and shared growth.",
    expectations: "A pleasant-natured, qualified lady (CA, MBA, Doctor, or Engineer) from a respectable Maheshwari/Vaishnav family who values relationships and is career-oriented.",
    initials: "AM",
    isRecentlyActive: true,
    isVerified: true,
    aiScore: 92
  },
  {
    id: "P6",
    name: "Divya Toshniwal",
    gender: "Bride",
    age: 25,
    height: "5'3\"",
    caste: "Maheshwari",
    gotra: "Kabra (Father) / Somani (Mother)",
    native: "Jodhpur, Rajasthan",
    rashi: "Virgo (Kanya)",
    nakshatra: "Uttara Phalguni",
    manglik: "Non-Manglik",
    education: "MBA - SPJIMR, Mumbai",
    occupation: "Brand Manager, FMCG Multinational",
    income: "₹24 Lakhs PA",
    location: "Mumbai, Maharashtra",
    familyType: "Traditional",
    familyDetails: "Father is a prominent industrialist (textiles) in Jodhpur. Mother manages a well-known cultural NGO. Elder brother manages the family manufacturing plants.",
    about: "A vibrant and energetic individual who loves modern marketing strategy as much as traditional Rajasthani festivals. I am organized, deeply empathetic, and enjoy reading self-growth books and learning folk arts.",
    expectations: "An ambitious, supportive, and loving partner, preferably in Mumbai or open to it, who is a well-placed corporate professional or entrepreneur.",
    initials: "DT",
    isRecentlyActive: false,
    isVerified: true,
    aiScore: 93
  },
  {
    id: "P7",
    name: "Siddharth Oswal",
    gender: "Groom",
    age: 28,
    height: "5'9\"",
    caste: "Oswal",
    gotra: "Bafna (Father) / Lodha (Mother)",
    native: "Udaipur, Rajasthan",
    rashi: "Scorpio (Vrishchika)",
    nakshatra: "Anuradha",
    manglik: "Non-Manglik",
    education: "Master of Finance - London School of Economics",
    occupation: "Investment Banker & Family Wealth Manager",
    income: "₹75 Lakhs PA",
    location: "London, UK",
    familyType: "Modern",
    familyDetails: "Parents are based in Udaipur; father is an exporter of marble and minerals. Mother is a social worker. One elder sister settled in Singapore.",
    about: "Global citizen with a Marwari soul. I enjoy golf, fine dining, and visiting art galleries, but nothing beats hot dal-baati-churma. I maintain a healthy work-life balance and value traditional Jain/Oswal ethics.",
    expectations: "An elegant, independent, and intellectually curious lady who is open to living abroad and values culture and mutual respect.",
    initials: "SO",
    isRecentlyActive: true,
    isVerified: false,
    aiScore: 90
  },
  {
    id: "P8",
    name: "Riya Kothari",
    gender: "Bride",
    age: 24,
    height: "5'5\"",
    caste: "Oswal",
    gotra: "Kothari (Father) / Singhvi (Mother)",
    native: "Jodhpur, Rajasthan",
    rashi: "Sagittarius (Dhanu)",
    nakshatra: "Mula",
    manglik: "Non-Manglik",
    education: "B.Des in Fashion Design - NIFT Delhi",
    occupation: "Creative Director, Luxury Sustainable Clothing Brand",
    income: "₹14 Lakhs PA",
    location: "Jaipur, Rajasthan",
    familyType: "Modern",
    familyDetails: "Father is a leading advocate in Jodhpur High Court. Mother is a designer herself. Younger brother studying in USA.",
    about: "Spirited, artistic, and deeply passionate about ethnic Rajasthani block prints. I run a design boutique in Jaipur. I love traveling, exploring rural artisan clusters, and practicing yoga. I cherish our family ethics and traditional values.",
    expectations: "A compassionate, supportive, and modern-thinking partner, preferably from a Jain/Oswal family, who appreciates creativity and respects independent careers.",
    initials: "RK",
    isRecentlyActive: true,
    isVerified: true,
    aiScore: 91
  },
  {
    id: "P9",
    name: "Vikramaditya Bhati",
    gender: "Groom",
    age: 30,
    height: "6'2\"",
    caste: "Rajput",
    gotra: "Bhati (Father) / Sodha (Mother)",
    native: "Jaisalmer, Rajasthan",
    rashi: "Capricorn (Makara)",
    nakshatra: "Uttarashadha",
    manglik: "Manglik (Anshik)",
    education: "M.Tech in Renewable Energy - IIT Delhi",
    occupation: "CEO, Desert Solar Enterprises & Ancestral Farmer",
    income: "₹45 Lakhs PA",
    location: "Jaisalmer, Rajasthan",
    familyType: "Royal Heritage",
    familyDetails: "Father is an active socio-political leader and royal descendant in Jaisalmer. Mother is a homemaker. Twin brother runs a heritage hotel in Jaisalmer.",
    about: "A proud son of the desert, dedicated to clean energy and community welfare. I balance my time between solar plants and ancestral agricultural lands. I love desert safaris, local folk music, and reading historical memoirs.",
    expectations: "A mature, graceful, and family-oriented bride who is comfortable with a combination of city and heritage town life, and respects our royal lineage and traditions.",
    initials: "VB",
    isRecentlyActive: false,
    isVerified: true,
    aiScore: 89
  },
  {
    id: "P10",
    name: "Meenakshi Sodha",
    gender: "Bride",
    age: 27,
    height: "5'6\"",
    caste: "Rajput",
    gotra: "Sodha (Father) / Bhati (Mother)",
    native: "Barmer, Rajasthan",
    rashi: "Pisces (Meena)",
    nakshatra: "Revati",
    manglik: "Manglik",
    education: "B.Arch - Sir J.J. College of Architecture, Mumbai",
    occupation: "Heritage Landscape Architect",
    income: "₹16 Lakhs PA",
    location: "Jodhpur, Rajasthan",
    familyType: "Traditional",
    familyDetails: "Father is a retired Senior IAS Officer of Rajasthan Cadre. Mother is a writer. One sister (Doctor) and one brother (Captain in Indian Army).",
    about: "Deeply connected to soil and structures. I work on landscaping palace gardens and ancient stepwells. I am refined, calm, and cherish classical literature and painting. I place high value on family integrity and royal virtues.",
    expectations: "An honorable and well-educated Rajput groom, preferably from Rajasthan/Mumbai, who values heritage, integrity, and mutual career support.",
    initials: "MS",
    isRecentlyActive: true,
    isVerified: true,
    aiScore: 94
  },
  {
    id: "P11",
    name: "Abhishek Baniya",
    gender: "Groom",
    age: 28,
    height: "5'8\"",
    caste: "Baniya",
    gotra: "Garg (Father) / Bansal (Mother)",
    native: "Alwar, Rajasthan",
    rashi: "Gemini (Mithuna)",
    nakshatra: "Ardra",
    manglik: "Non-Manglik",
    education: "B.Tech & M.Tech Dual Degree - IIT Kharagpur",
    occupation: "Senior Product Manager, FinTech Unicorn",
    income: "₹48 Lakhs PA",
    location: "Bangalore, Karnataka",
    familyType: "Traditional",
    familyDetails: "Father owns a renowned wholesale grains trade network in Alwar. Mother is a homemaker. Elder brother runs a tech firm in Pune.",
    about: "Analytical, humorous, and highly adaptive. While I love the fast-paced tech lifestyle in Bangalore, I find peace in traditional values and regular family visits. I enjoy amateur theater, backpacking, and playing chess.",
    expectations: "A career-oriented, cheerful, and understanding girl who can balance professional ambitions with warm household ethics. Open to relocate to Bangalore.",
    initials: "AB",
    isRecentlyActive: true,
    isVerified: false,
    aiScore: 88
  },
  {
    id: "P12",
    name: "Nehal Agrawal",
    gender: "Bride",
    age: 25,
    height: "5'4\"",
    caste: "Baniya",
    gotra: "Goyal (Father) / Mittal (Mother)",
    native: "Bharatpur, Rajasthan",
    rashi: "Aquarius (Kumbha)",
    nakshatra: "Shatabhisha",
    manglik: "Non-Manglik",
    education: "Chartered Accountant (CA) & B.Com - SRCC Delhi",
    occupation: "Financial Analyst, Top Investment Fund",
    income: "₹28 Lakhs PA",
    location: "Delhi NCR",
    familyType: "Traditional",
    familyDetails: "Father is a practicing CA and financial advisor in Bharatpur. Mother is a teacher. One younger brother studying at BITS Pilani.",
    about: "Driven, logical, and highly organized, yet soft-hearted and deeply affectionate. I love exploring Delhi's history, food blogs, and practicing classical singing. I value ethical conduct and strong familial relationships.",
    expectations: "A progressive, highly qualified professional, preferably based in Delhi NCR or Bangalore, who shares similar moral grounds and supports my career.",
    initials: "NA",
    isRecentlyActive: true,
    isVerified: true,
    aiScore: 97
  },
  {
    id: "P13",
    name: "Yashvardhan Saxena",
    gender: "Groom",
    age: 29,
    height: "5'10\"",
    caste: "Kayastha",
    gotra: "Srivastava (Father) / Mathur (Mother)",
    native: "Kota, Rajasthan",
    rashi: "Virgo (Kanya)",
    nakshatra: "Hasta",
    manglik: "Non-Manglik",
    education: "M.Tech in Data Science - BITS Pilani",
    occupation: "Lead AI Engineer, Multinational Tech Conglomerate",
    income: "₹38 Lakhs PA",
    location: "Gurgaon, Haryana",
    familyType: "Traditional",
    familyDetails: "Father is a retired Chief Engineer, Irrigation Dept. Mother is a senior government lawyer. One sister who is a civil architect.",
    about: "A blend of analytical mindset and literary passion. I write Hindi poetry, love classical instrumentals, and enjoy mentoring young minds in technology. Deeply attached to my family and hometown.",
    expectations: "An educated, cultured, and expressive partner who enjoys literature/arts, maintains an independent career, and values strong family bonds.",
    initials: "YS",
    isRecentlyActive: false,
    isVerified: true,
    aiScore: 89
  },
  {
    id: "P14",
    name: "Kriti Mathur",
    gender: "Bride",
    age: 26,
    height: "5'5\"",
    caste: "Kayastha",
    gotra: "Mathur (Father) / Saxena (Mother)",
    native: "Jaipur, Rajasthan",
    rashi: "Taurus (Vrishabha)",
    nakshatra: "Krittika",
    manglik: "Non-Manglik",
    education: "M.A. in English Literature & Journalism - Delhi University",
    occupation: "Senior Editor & Feature Journalist, National Media House",
    income: "₹16 Lakhs PA",
    location: "Delhi NCR",
    familyType: "Traditional",
    familyDetails: "Father is a retired Director of Rajasthan Tourism. Mother is a published novelist and English professor. One younger sister working in UX design.",
    about: "Articulate, liberal, yet traditional at heart. I write extensively on cultural landscapes and heritage culinary stories. I love traveling, theater, and culinary experimentation. I maintain deep ties with our native roots.",
    expectations: "An open-minded, well-read, and professionally established gentleman who values intellect, emotional depth, and respects a woman's creative freedom.",
    initials: "KM",
    isRecentlyActive: true,
    isVerified: true,
    aiScore: 92
  }
];

window.SEED_PROFILES = SEED_PROFILES;
